/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("sap.zzem.fo.visibility.util.formatter");sap.zzem.fo.visibility.util.formatter={};
sap.zzem.fo.visibility.util.formatter.init=function(r){sap.zzem.fo.visibility.util.formatter._oBundle=r;jQuery.sap.require("sap.ui.core.format.DateFormat");sap.zzem.fo.visibility.util.formatter.LocalDateFormatter=sap.ui.core.format.DateFormat.getDateInstance();sap.zzem.fo.visibility.util.formatter.LocalTimeFormatter=sap.ui.core.format.DateFormat.getTimeInstance();sap.zzem.fo.visibility.util.formatter.EventMessageDateFormatter=sap.ui.core.format.DateFormat.getDateInstance({pattern:"yyyyMMdd"});sap.zzem.fo.visibility.util.formatter.EventMessageTimeFormatter=sap.ui.core.format.DateFormat.getTimeInstance({pattern:"hhmmss"})};
sap.zzem.fo.visibility.util.formatter.AddressFormatter=function(a){if(a){return a.replace(/\//g,"\n")}return""};
sap.zzem.fo.visibility.util.formatter.ObjectFormatter=function(I,D){if(D){if(I){return I+" ("+D+")"}return D}if(I){return I}return""};
sap.zzem.fo.visibility.util.formatter.MinusFormatter=function(I,D){if(D){if(I){return I+" - "+D}return D}if(I){return I}return""};
sap.zzem.fo.visibility.util.formatter.iconFormatter=function(e){switch(e){case"01":return"accept";case"02":return"alert";case"03":return"future";case"04":return"status-inactive";case"05":return"warning2";case"06":case"07":return"lateness";default:return""}};
sap.zzem.fo.visibility.util.formatter.iconTooltipFormatter=function(e){var E="";switch(e){case"01":E=sap.zzem.fo.visibility.util.formatter._oBundle.getText("EVENT_STATUS_REPORTED");break;case"02":E=sap.zzem.fo.visibility.util.formatter._oBundle.getText("EVENT_STATUS_OVERDUE");break;case"03":E=sap.zzem.fo.visibility.util.formatter._oBundle.getText("EVENT_STATUS_UNREP_DATE");break;case"04":E=sap.zzem.fo.visibility.util.formatter._oBundle.getText("EVENT_STATUS_UNREP");break;case"05":E=sap.zzem.fo.visibility.util.formatter._oBundle.getText("EVENT_STATUS_UNEXPECTED");break;case"06":E=sap.zzem.fo.visibility.util.formatter._oBundle.getText("EVENT_STATUS_REPORTED_EARLY");break;case"07":E=sap.zzem.fo.visibility.util.formatter._oBundle.getText("EVENT_STATUS_REPORTED_LATE");break;default:E=""}return E};
sap.zzem.fo.visibility.util.formatter.DateTimeFormatter=function(d,t){if(!t){t=""}if(d){var u=new Date(d.getUTCFullYear().toString(),d.getUTCMonth().toString(),d.getUTCDate().toString(),d.getUTCHours().toString(),d.getUTCMinutes().toString(),d.getUTCSeconds().toString());return sap.zzem.fo.visibility.util.formatter.LocalDateFormatter.format(u)+"\n "+sap.zzem.fo.visibility.util.formatter.LocalTimeFormatter.format(u)+" "+t}return" "};
sap.zzem.fo.visibility.util.formatter.DateTimeDialogFormatter=function(d,t){if(!t){t=""}if(d){var u=new Date(d.getUTCFullYear().toString(),d.getUTCMonth().toString(),d.getUTCDate().toString(),d.getUTCHours().toString(),d.getUTCMinutes().toString(),d.getUTCSeconds().toString());return sap.zzem.fo.visibility.util.formatter.LocalDateFormatter.format(u)+" "+sap.zzem.fo.visibility.util.formatter.LocalTimeFormatter.format(u)+" "+t}return" "};
sap.zzem.fo.visibility.util.formatter.countFormatter=function(c){try{var n=parseInt(c,10)}catch(e){return 0}if(n>999){return">1k"}if(isNaN(n)){return 0}return n};
sap.zzem.fo.visibility.util.formatter.valueStateFormatter=function(v){if(!v||v.indexOf("ValueState")!==-1){return sap.ui.core.ValueState.None}if(v==="None"||v==="Error"||v==="Success"||v==="Warning"){return v}return sap.ui.core.ValueState.None};
sap.zzem.fo.visibility.util.formatter.reportEventFormatter=function(e){if(e==="05"){return false}return true};